spring:
  application:
    name: cacodemon
  datasource:
    url: jdbc:postgresql://localhost:5432/cacodemon
  flyway:
    enabled: true
    baseline-version: 1.0
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    target: latest
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: potgres
    password: 123456
    default-schema: ${spring.jpa.properties.hibernate.default_schema}