spring:
  application:
    name: cacodemon
  datasource:
    url: jdbc:postgresql://localhost:5432/cacodemon
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-version: 1.0
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    target: latest
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
